/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.uv.tcswpractica04;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author carlos
 */
public class DepartamentoGUI extends javax.swing.JFrame {
private DefaultListModel<String> listModelDept;

    /**
     * Creates new form DepartamentoGUI
     */
    public DepartamentoGUI() {
        initComponents();
        // Inicializar modelo para la JList (para mostrar empleados)
        listModelDept = new DefaultListModel<>();
        lstDeptEmpleados.setModel(listModelDept);

    }
// Inicializar modelo para la JList (para mostrar empleados)
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDeptClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDeptNombre = new javax.swing.JTextField();
        btnDeptGuardar = new javax.swing.JButton();
        btnDeptCargar = new javax.swing.JButton();
        btnDeptEliminar = new javax.swing.JButton();
        spDeptEmpleados = new javax.swing.JScrollPane();
        lstDeptEmpleados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clave");

        txtDeptClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptClaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        txtDeptNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptNombreActionPerformed(evt);
            }
        });

        btnDeptGuardar.setText("Guardar");
        btnDeptGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeptGuardarActionPerformed(evt);
            }
        });

        btnDeptCargar.setText("Cargar");
        btnDeptCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeptCargarActionPerformed(evt);
            }
        });

        btnDeptEliminar.setText("Eliminar");
        btnDeptEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeptEliminarActionPerformed(evt);
            }
        });

        lstDeptEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spDeptEmpleados.setViewportView(lstDeptEmpleados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeptClave)
                            .addComponent(txtDeptNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(spDeptEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeptEliminar)
                    .addComponent(btnDeptGuardar)
                    .addComponent(btnDeptCargar))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDeptClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeptGuardar))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDeptNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeptCargar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnDeptEliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(spDeptEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Inicializar modelo para la JList (para mostrar empleados)


    private void txtDeptClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeptClaveActionPerformed

    private void txtDeptNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeptNombreActionPerformed

    private void btnDeptEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeptEliminarActionPerformed
        String claveText = txtDeptClave.getText().trim();
    if (claveText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Introduce la clave del departamento a eliminar.");
        return;
    }

    Long id;
    try {
        id = Long.parseLong(claveText);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "La clave debe ser un número.");
        return;
    }

    DAODepartamentos dao = new DAODepartamentos();
    Departamento eliminado = dao.eliminar(id); // debe estar implementado en el DAO

    if (eliminado != null) {
        JOptionPane.showMessageDialog(this, "Departamento eliminado: " + eliminado.getClave());
        txtDeptClave.setText("");
        txtDeptNombre.setText("");
        listModelDept.clear();
    } else {
        JOptionPane.showMessageDialog(this, "No existe departamento con clave: " + id);
    }

    }//GEN-LAST:event_btnDeptEliminarActionPerformed

    private void btnDeptGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeptGuardarActionPerformed
        String nombre = txtDeptNombre.getText().trim();
    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Escribe el nombre del departamento.");
        return;
    }

    Departamento d = new Departamento();
    d.setNombre(nombre);

    DAODepartamentos dao = new DAODepartamentos();
    dao.guardar(d); // guarda; la secuencia debe asignar d.getClave()

    JOptionPane.showMessageDialog(this, "Departamento guardado con clave: " + d.getClave());
    txtDeptNombre.setText("");

    }//GEN-LAST:event_btnDeptGuardarActionPerformed

    private void btnDeptCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeptCargarActionPerformed
        String claveText = txtDeptClave.getText().trim();
    if (claveText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Introduce la clave del departamento a cargar.");
        return;
    }

    Long id;
    try {
        id = Long.parseLong(claveText);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "La clave debe ser un número.");
        return;
    }

    DAODepartamentos dao = new DAODepartamentos();
    Departamento d = dao.findByID(id);
    if (d == null) {
        JOptionPane.showMessageDialog(this, "Departamento no encontrado para la clave: " + id);
        listModelDept.clear();
        txtDeptNombre.setText("");
        return;
    }

    // mostrar nombre en el campo
    txtDeptNombre.setText(d.getNombre());

    // obtener empleados del departamento y mostrarlos en la JList
    List<Empleados> empleados = dao.getEmpleadosByDepartamento(id);
    listModelDept.clear();
    for (Empleados emp : empleados) {
        listModelDept.addElement(emp.getClave() + " - " + emp.getNombre());
    }
    }//GEN-LAST:event_btnDeptCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartamentoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeptCargar;
    private javax.swing.JButton btnDeptEliminar;
    private javax.swing.JButton btnDeptGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList<String> lstDeptEmpleados;
    private javax.swing.JScrollPane spDeptEmpleados;
    private javax.swing.JTextField txtDeptClave;
    private javax.swing.JTextField txtDeptNombre;
    // End of variables declaration//GEN-END:variables
}
